stages:
  transpose:
    cmd: powershell Copy-Item input/azurite_db_table.json output/azurite_db_table-output.json
    deps:
      - input/azurite_db_table.json
    outs:
      - output/azurite_db_table-output.json
